# Generated by Django 6.0.2 on 2026-02-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Draft"), (1, "Published")], default=0
            ),
        ),
    ]
