# Generated by Django 6.0.2 on 2026-03-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0007_social"),
    ]

    operations = [
        migrations.DeleteModel(
            name="About",
        ),
        migrations.DeleteModel(
            name="Social",
        ),
    ]
