# Generated by Django 6.0.3 on 2026-03-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0009_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="Comment",
            new_name="comment",
        ),
    ]
