# Generated by Django 6.0.3 on 2026-03-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0010_rename_comment_comment_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
